# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mgrad_rt',
                'doc_host': 'https://robitsar.github.io',
                'git_url': 'https://github.com/robitsar/mgrad_rt',
                'lib_path': 'mgrad_rt'},
  'syms': {'mgrad_rt.core': {'mgrad_rt.core.foo': ('core.html#foo', 'mgrad_rt/core.py')}}}
